language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# commands to install dependencies
install:
  - python setup.py -q install
  - git clone https://github.com/ewels/MultiQC_TestData.git test_data
  - cd test_data
# commands to run tests
script:
  - multiqc data
  - multiqc data -f -i "Forced Report" -z -m fastqc -n custom_fn --no-data-dir
  - multiqc data -f -z -v --flat -e fastqc
  - multiqc -o tests/multiqc_report_dev -t default_dev -k json --file-list data/special_cases/file_list.txt
  
