language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
# command to install dependencies
install: python setup.py -q install
# command to run tests
script: multiqc -f -o tests/multiqc_report tests/data
