language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
# command to install dependencies
install: python setup.py -q install
# command to run tests
script: multiqc -v -o tests/multiqc_report tests/data
